version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=check
      - MARIADB_PASSWORD=checking
      - MARIADB_DATABASE=echeck
    volumes:
      - ../db:/bitnami/mariadb 

  app:
    tty: true # Enables debugging capabilities when attached to this container.
    build:
      context: ../e-check_api
      dockerfile: Dockerfile    
    links:
      - mariadb:db.ec.chatops.in
    environment:
      - RAILS_ENV=production
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ../e-check_api:/app

  dashboard:
    build:
      context: ../e-check-dashboard
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ../e-check-dashboard:/app

  frontend:
    build:
      context: ../e-check-frontend
      dockerfile: Dockerfile
    ports:
      - 8081:80
    volumes:
      - ../e-check-frontend:/app

  lbs:
    build:
      context: ../lbs
      dockerfile: Dockerfile
    ports:
      - 80:80
    links:
      - app:api
      - dashboard
      - frontend
    volumes:
      - ../lbs/conf:/etc/nginx/conf.d
      - ../lbs/html:/usr/share/nginx/html
    depends_on:
      - frontend
      - dashboard
      - app
