version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=check
      - MARIADB_PASSWORD=checking
      - MARIADB_DATABASE=echeck
      
  app:
    tty: true # Enables debugging capabilities when attached to this container.
    build:
      context: ../e-check_api
      dockerfile: Dockerfile    
    # labels:
    #   kompose.service.type: nodeport
    # environment:
    #   - DATABASE_URL=mysql2://mariadb/my_app_development
    depends_on:
      - mariadb
    ports:
      - 80:3000
    volumes:
      - ../e-check_api:/app
